### ISSUE TITLE
getting null pointer exception

### ISSUE THREAD

**Issue by Aviswanathan** [mikepenz/Android-ActionItemBadge#19]
in my menu xml i placed this..
```xml
<item android:id="@+id/action_carticon" android:title="@string/action_example"
        app:showAsAction="always"
        android:orderInCategory="100"
        android:actionLayout="@layout/menu_badge"
        />
```
and in my create options menu i used this 
```java
ActionItemBadge.update(this, menu.findItem(R.id.action_carticon), getResources().getDrawable(R.drawable.ic_launcher), ActionItemBadge.BadgeStyle.GREEN,5);
```
what i done wrong if i create menu item programatically works great.if the count is zero need to hide the item badge.is there any possible.

**Comment by mikepenz** [comment]
@Aviswanathan can you also post the stackTrace?

**Comment by shakmak** [comment]
java.lang.NullPointerException
            at com.mikepenz.actionitembadge.library.ActionItemBadge.setBackground(ActionItemBadge.java:266)
            at com.mikepenz.actionitembadge.library.ActionItemBadge.update(ActionItemBadge.java:203)
            at com.mikepenz.actionitembadge.library.ActionItemBadge.update(ActionItemBadge.java:192)
            at com.twigly.app.ui.activity.CheckOutActivity.onCreateOptionsMenu(CheckOutActivity.java:201)
            at android.app.Activity.onCreatePanelMenu(Activity.java:2538)
            at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:277)
            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:273)
            at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
            at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:449)
            at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:66)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mikepenz** [comment]
@shakmak you mix up normal style and large style?

**Comment by mikepenz** [comment]
Should be fixed in the latest version
